Repository braph-software/BRAPH-2, pull requests merged in 2022-04, with the labels that each got.

#1281 NN braph2 files
  braph2genesis/pipelines/connectivity NN/pipeline_neural_networks_classification_con_wu.braph2
  braph2genesis/pipelines/connectivity NN/pipeline_neural_networks_classification_cross_validation_con_wu.braph2
  braph2genesis/pipelines/connectivity-functional multiplex NN/pipeline_neural_networks_classification_con_fun_mp_wu.braph2
  braph2genesis/pipelines/functional NN/pipeline_neural_networks_regression_cross_validation_fun_wu.braph2
  braph2genesis/pipelines/functional NN/pipeline_neural_networks_regression_fun_wu.braph2
  braph2genesis/pipelines/structural NN/pipeline_neural_networks_classification_st.braph2
Labels: GUI, neuralnetworks

#1288 Bug fix for set feature mask in NN group
  braph2genesis/neuralnetworks/_NNClassifierDataSplit.gen.m
  braph2genesis/neuralnetworks/_NNClassifierEvaluator.gen.m
  braph2genesis/neuralnetworks/_NNRegressorDataSplit.gen.m
Labels: neuralnetworks

#1291 Graph measure compatibility check and small fixes for NN GUI
  braph2genesis/neuralnetworks/_NNClassifierCrossValidation.gen.m
  braph2genesis/pipelines/connectivity NN/_NNData_CON_BUD.gen.m
  braph2genesis/pipelines/connectivity NN/_NNData_CON_WU.gen.m
  braph2genesis/pipelines/connectivity NN/example_NN_CON_WU_Classification_AdjacencyMatrix.m
  braph2genesis/pipelines/connectivity NN/example_NN_CON_WU_Classification_GraphMeasures.m
  braph2genesis/pipelines/connectivity NN/example_NN_CON_WU_Regression_AdjacencyMatrix.m
  braph2genesis/pipelines/connectivity-functional multiplex NN/_NNData_CON_FUN_MP_WU.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex NN/example_NN_CON_FUN_MP_WU_Classification_GraphMeasures.m
  braph2genesis/pipelines/functional NN/_NNData_FUN_WU.gen.m
  braph2genesis/pipelines/functional NN/example_NN_FUN_WU_Classification_AdjacencyMatrix.m
  braph2genesis/pipelines/functional NN/example_NN_FUN_WU_Classification_GraphMeasures.m
  braph2genesis/pipelines/functional NN/example_NN_FUN_WU_Regression_AdjacencyMatrix.m
  braph2genesis/pipelines/structural NN/example_NN_ST_Classification.m
  braph2genesis/pipelines/structural NN/example_NN_ST_Regression.m
  braph2genesis/src/gui/layouts/NNData_CON_WU.layout
  braph2genesis/src/gui/layouts/NNGroup.layout
  braph2genesis/src/nn/_NNData.gen.m
  braph2genesis/src/nn/_NNGroup.gen.m
  braph2genesis/src/nn/_PPNNData_Input_Type.gen.m
  braph2genesis/src/nn/_PPNNData_Measures.gen.m
Labels: GUI, neuralnetworks

#1296 Finalize NN GUI in general
  braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
  braph2genesis/neuralnetworks/_NNClassifierDataSplit.gen.m
  braph2genesis/neuralnetworks/_NNRegressorDNN.gen.m
  braph2genesis/neuralnetworks/_NNRegressorDataSplit.gen.m
  braph2genesis/neuralnetworks/_PPNNClassifierEvaluator_AUC.gen.m
  braph2genesis/neuralnetworks/_PPNNClassifierEvaluator_Confusion_Matrix.gen.m
  braph2genesis/pipelines/connectivity NN/_NNData_CON_WU.gen.m
  braph2genesis/pipelines/connectivity NN/pipeline_neural_networks_classification_con_wu.braph2
  braph2genesis/pipelines/connectivity-functional multiplex NN/pipeline_neural_networks_classification_con_fun_mp_wu.braph2
  braph2genesis/pipelines/functional NN/pipeline_neural_networks_regression_fun_wu.braph2
  braph2genesis/pipelines/structural NN/pipeline_neural_networks_classification_st.braph2
  braph2genesis/src/gui/_PlotPropSmartVector.gen.m
  braph2genesis/src/gui/layouts/NNClassifierDNN.layout
  braph2genesis/src/gui/layouts/NNClassifierEvaluator.layout
  braph2genesis/src/gui/layouts/NNSubject.layout
  braph2genesis/src/nn/_NNDataSplit.gen.m
  braph2genesis/src/nn/_NNSubject.gen.m
  braph2genesis/src/nn/_PPNNBase_Model.gen.m
  braph2genesis/src/nn/_PPNNData_GR_NN.gen.m
  braph2genesis/src/nn/_PPNNData_Input_Type.gen.m
  braph2genesis/src/nn/_PPNNData_Measures.gen.m
  braph2genesis/src/nn/_PPNNSubject_Input.gen.m
Labels: GUI, neuralnetworks

#1304 Fix the unitest for NN related files
  braph2genesis/neuralnetworks/_NNRegressorCrossValidation.gen.m
  braph2genesis/pipelines/structural NN/_NNData_ST.gen.m
  braph2genesis/pipelines/structural multimodality NN/_NNData_ST_MM.gen.m
Labels: neuralnetworks

#1305 NN GUI for regression and cross-validation
  braph2genesis/neuralnetworks/_NNClassifierCrossValidation.gen.m
  braph2genesis/neuralnetworks/_NNRegressorDNN.gen.m
  braph2genesis/neuralnetworks/_NNRegressorEvaluator.gen.m
  braph2genesis/neuralnetworks/_PPNNClassifierCrossValidation_AUC.gen.m
  braph2genesis/neuralnetworks/_PPNNClassifierCrossValidation_Confusion_Matrix.gen.m
  braph2genesis/neuralnetworks/_PPNNCrossValidation_Feature_Map.gen.m
  braph2genesis/neuralnetworks/_PPNNCrossValidation_NNDict.gen.m
  braph2genesis/neuralnetworks/_PPNNRegressorEvaluator_Scatter_Chart.gen.m
  braph2genesis/src/gui/layouts/NNClassifierCrossValidation.layout
  braph2genesis/src/gui/layouts/NNClassifierEvaluator.layout
  braph2genesis/src/gui/layouts/NNData_FUN_WU.layout
  braph2genesis/src/gui/layouts/NNRegressorDNN.layout
  braph2genesis/src/gui/layouts/NNRegressorDataSplit.layout
  braph2genesis/src/gui/layouts/NNRegressorEvaluator.layout
  braph2genesis/src/gui/layouts/NNSubject.layout
Labels: GUI, neuralnetworks

#1309 Fix IM_ERR
  braph2genesis/pipelines/connectivity-functional multiplex/_ImporterGroupSubjectCON_FUN_MP_TXT.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex/_ImporterGroupSubjectCON_FUN_MP_XLS.gen.m
  braph2genesis/pipelines/connectivity/_ImporterGroupSubjectCON_TXT.gen.m
  braph2genesis/pipelines/connectivity/_ImporterGroupSubjectCON_XLS.gen.m
  braph2genesis/pipelines/functional/_ImporterGroupSubjectFUN_TXT.gen.m
  braph2genesis/pipelines/functional/_ImporterGroupSubjectFUN_XLS.gen.m
  braph2genesis/pipelines/structural/_ImporterGroupSubjectST_TXT.gen.m
  braph2genesis/pipelines/structural/_ImporterGroupSubjectST_XLS.gen.m
  braph2genesis/src/atlas/_ImporterBrainAtlasTXT.gen.m
  braph2genesis/src/atlas/_ImporterBrainAtlasXLS.gen.m
  braph2genesis/src/gui/_ImporterPipelineBRAPH2.gen.m
  braph2genesis/src/gui/_PPPipeline_PSDict.gen.m
Labels: BRAPH2Genesis

#1307 Finalization for all 6 NN braph2 files
  braph2genesis/neuralnetworks/_NNClassifierCrossValidation.gen.m
  braph2genesis/neuralnetworks/_NNClassifierDataSplit.gen.m
  braph2genesis/neuralnetworks/_NNRegressorCrossValidation.gen.m
  braph2genesis/neuralnetworks/_NNRegressorDataSplit.gen.m
  braph2genesis/neuralnetworks/_NNRegressorEvaluator.gen.m
  braph2genesis/neuralnetworks/_PPNNCrossValidation_Feature_Map.gen.m
  braph2genesis/pipelines/connectivity NN/pipeline_neural_networks_classification_con_wu.braph2
  braph2genesis/pipelines/connectivity-functional multiplex NN/_NNData_CON_FUN_MP_WU.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex NN/pipeline_neural_networks_classification_con_fun_mp_wu.braph2
  braph2genesis/pipelines/functional NN/_NNData_FUN_WU.gen.m
  braph2genesis/pipelines/functional NN/pipeline_neural_networks_regression_cross_validation_fun_wu.braph2
  braph2genesis/pipelines/functional NN/pipeline_neural_networks_regression_fun_wu.braph2
  braph2genesis/pipelines/structural NN/pipeline_neural_networks_classification_st.braph2
  braph2genesis/src/atlas/_PlotBrainNN.gen.m
  braph2genesis/src/gui/layouts/NNClassifierCrossValidation.layout
  braph2genesis/src/gui/layouts/NNClassifierEvaluator.layout
  braph2genesis/src/gui/layouts/NNData_CON_FUN_MP_WU.layout
  braph2genesis/src/gui/layouts/NNData_CON_WU.layout
  braph2genesis/src/gui/layouts/NNData_ST.layout
  braph2genesis/src/gui/layouts/NNRegressorCrossValidation.layout
  braph2genesis/src/nn/_PPNNEvaluator_Feature_Map.gen.m
  braph2genesis/src/nn/_PPNNSubject_Input.gen.m
Labels: GUI, neuralnetworks

#1320 1319-yc-failedUnitTests
  braph2genesis/measures/_Degree.gen.m
  braph2genesis/measures/_DegreeAv.gen.m
  braph2genesis/measures/_Distance.gen.m
  braph2genesis/measures/_Modularity.gen.m
  braph2genesis/neuralnetworks/_NNClassifierCrossValidation.gen.m
  braph2genesis/neuralnetworks/_NNRegressorCrossValidation.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex NN/_NNData_CON_FUN_MP_WU.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex/_ImporterGroupSubjectCON_FUN_MP_TXT.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex/_ImporterGroupSubjectCON_FUN_MP_XLS.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex/_SubjectCON_FUN_MP.gen.m
  braph2genesis/pipelines/connectivity-functional multiplex/example data CON-FUN_MP/txt/functional/GroupName1/covariates/GroupName1_covariates.txt
  braph2genesis/pipelines/connectivity-functional multiplex/example data CON-FUN_MP/txt/functional/GroupName2/covariates/GroupName2_covariates.txt
  braph2genesis/pipelines/functional NN/_NNData_FUN_WU.gen.m
  braph2genesis/pipelines/structural NN/_NNData_ST.gen.m
  braph2genesis/pipelines/structural multimodality NN/_NNData_ST_MM.gen.m
  braph2genesis/src/nn/_NNData.gen.m
Labels: bug, test

#1325 1322 yc NN importing error
  braph2genesis/src/nn/_NNBase.gen.m
Labels: bug, neuralnetworks

#1327 Customizable global constants and save/load functions
  braph2genesis/genesis/create_Element.m
  braph2genesis/src/ds/Element.m
  braph2genesis/src/ds/Format.m
  braph2genesis/src/ds/_ETB.gen.m
  braph2genesis/src/util/BRAPH2.m
  braph2genesis/src/util/_BRAPH2Constants.gen.m
  braph2genesis/tmp.m
Labels: enhancement

#1329 Update NET prop
  braph2genesis/neuralnetworks/_NNClassifierDNN.gen.m
  braph2genesis/neuralnetworks/_NNClassifierEvaluator.gen.m
  braph2genesis/neuralnetworks/_NNRegressorDNN.gen.m
  braph2genesis/neuralnetworks/_NNRegressorEvaluator.gen.m
  braph2genesis/src/ds/Element.m
  braph2genesis/src/ds/Format.m
  braph2genesis/src/ds/_ETG.gen.m
  braph2genesis/src/ds/test_Format.m
  braph2genesis/src/nn/_NNBase.gen.m
  braph2genesis/src/nn/_PPNNBase_Model.gen.m
Labels: neuralnetworks

#1334 1333-yc-toolboxCheckFix
  braph2genesis/_braph2/braph2.m
  braph2genesis/neuralnetworks/_NNClassifierCrossValidation.gen.m
  braph2genesis/neuralnetworks/_NNRegressorCrossValidation.gen.m
  braph2genesis/src/util/BRAPH2.m
Labels: bug

#1339 1338-yc-matlab-version2020b
  braph2genesis/src/ds/Element.m
  braph2genesis/src/ds/_ETG.gen.m
Labels: enhancement

#1342 1341 ywc etg test bug
  braph2genesis/src/ds/_ETG.gen.m
Labels: bug, neuralnetworks

#1350 Add pipeline GUI for FUN NN cross-validation classification
  braph2genesis/pipelines/functional NN/pipeline_neural_networks_classification_cross_validation_fun_wu.braph2
Labels: GUI, neuralnetworks

#1347 1346 ac multilayer measures revision
  braph2genesis/measures/_CategoricalPersistence.gen.m
  braph2genesis/measures/_DegreeOverlap.gen.m
  braph2genesis/measures/_DegreeOverlapAv.gen.m
  braph2genesis/measures/_Flexibility.gen.m
  braph2genesis/measures/_FlexibilityAv.gen.m
  braph2genesis/measures/_Modularity.gen.m
  braph2genesis/measures/_MultilayerCommunityStructure.gen.m
  braph2genesis/measures/_MultilayerModularity.gen.m
  braph2genesis/measures/_MultiplexClusteringAv.gen.m
  braph2genesis/measures/_MultiplexInParticipation.gen.m
  braph2genesis/measures/_MultiplexOutParticipation.gen.m
  braph2genesis/measures/_MultiplexParticipation.gen.m
  braph2genesis/measures/_MultiplexParticipationAv.gen.m
  braph2genesis/measures/_OverlappingOutStrengthAv.gen.m
  braph2genesis/measures/_Persistence.gen.m
  braph2genesis/measures/_WeightedMultiplexInParticipation.gen.m
  braph2genesis/measures/_WeightedMultiplexOutParticipation.gen.m
  braph2genesis/measures/_WeightedMultiplexParticipation.gen.m
  braph2genesis/measures/_WeightedMultiplexParticipationAv.gen.m
Labels: documentation, measure

#1352 BUG in PlotBrainGraphEnsemble - Sphere
  braph2genesis/src/atlas/_PlotBrainGraphEnsemble.gen.m
Labels: bug

#1354 BUG in PPCompareEnsemble_FUN_CPDict_WU.gen.m
  braph2genesis/pipelines/functional/_PPCompareEnsemble_FUN_CPDict_WU.gen.m
Labels: bug

#1356 Add pipeline GUI for CON-FUN NN cross-validation classification
  braph2genesis/pipelines/connectivity-functional multiplex NN/pipeline_neural_networks_classification_cross_validation_con_fun_mp_wu.braph2
Labels: GUI, neuralnetworks
