Repository braph-software/BRAPH-2, pull requests merged in 2023-10, with the labels that each got.

#1558 fun bud tutorial
  tutorials/pipelines/tut_a_con_bud/readme.md
  tutorials/pipelines/tut_a_con_bud/tut_a_con_bud.pdf
  tutorials/pipelines/tut_a_con_bud/tut_a_con_bud.tex
  tutorials/pipelines/tut_a_fun_bud/fig02.jpg
  tutorials/pipelines/tut_a_fun_bud/fig03.jpg
  tutorials/pipelines/tut_a_fun_bud/fig04.jpg
  tutorials/pipelines/tut_a_fun_bud/fig05.jpg
  tutorials/pipelines/tut_a_fun_bud/fig06.jpg
  tutorials/pipelines/tut_a_fun_bud/fig07.jpg
  tutorials/pipelines/tut_a_fun_bud/fig08.jpg
  tutorials/pipelines/tut_a_fun_bud/fig09.jpg
  tutorials/pipelines/tut_a_fun_bud/fig10.jpg
  tutorials/pipelines/tut_a_fun_bud/fig11abc.jpg
  tutorials/pipelines/tut_a_fun_bud/fig11d1.jpg
  tutorials/pipelines/tut_a_fun_bud/fig11d2.jpg
  tutorials/pipelines/tut_a_fun_bud/fig12a.jpg
  tutorials/pipelines/tut_a_fun_bud/fig12bc.jpg
  tutorials/pipelines/tut_a_fun_bud/tut_a_con_bud.pdf
  tutorials/pipelines/tut_a_fun_bud/tut_a_con_bud.tex
  tutorials/pipelines/tut_a_fun_bud/tut_a_fun_bud.tex
Labels: documentation

#1567 regenerate function
  braph2genesis/_braph2/braph2.m
  braph2genesis/genesis/regenerate.m
  temp.m
Labels: BRAPH2Genesis

#1557 Gv 1556 BRAPH2GUI popup
  braph2/src/gui/BRAPH2GUI.m
  braph2/src/gui/ExporterPipelineBRAPH2.m
  braph2/src/util/BRAPH2.m
  braph2genesis/src/gui/BRAPH2GUI.m
  braph2genesis/src/gui/_ExporterPipelineBRAPH2.gen.m
  braph2genesis/src/util/BRAPH2.m
Labels: enhancement

#1613 PF management for analyze group
  braph2/src/analysis/AnalyzeGroupPP_G.m
  braph2/src/analysis/CompareGroupPP_CpDict.m
  braph2/src/analysis/ComparisonGroup.m
  braph2/src/analysis/test_AnalyzeGroupPP_G.m
  braph2/src/analysis/test_CompareGroupPP_CpDict.m
  braph2genesis/src/analysis/_AnalyzeGroupPP_G.gen.m
  braph2genesis/src/analysis/_CompareGroupPP_CpDict.gen.m
  braph2genesis/src/analysis/_ComparisonGroup.gen.m
Labels: enhancement, analysis, GUI, comparison

#1684 FIX BUG: pipeline_functional_comparison_but.braph2 & pipeline_functional_analysis_bud.braph2
  braph2genesis/pipelines/functional/pipeline_functional_analysis_bud.braph2
  braph2genesis/pipelines/functional/pipeline_functional_comparison_but.braph2
Labels: bug
